### ISSUE TITLE
Comparison with React-Virtualized/prod-readiness

### ISSUE THREAD

**Issue by alexkrolick** [gridgrid/grid-react-adapter#1]
We are considering using `grid` in a React app. How does this adapter compare to libraries like [React Virtualized](https://bvaughn.github.io/react-virtualized/)? Is performance comparable? Is it bundleable with Webpack? What is the API?

**Comment by scamden** [comment]
I haven’t personally used react virtualized but I have yet to find a grid implementation with better scroll performance (and I’ve tried many). I am currently using it with web pack so yes. The api is discoverable via the types but if you have specific questions I’m also happy to answer them. Like I mentioned on the grid repo this project is relatively new so I can also help add features if things are missing here (prs are also welcome). The grid itself is quite feature rich so usually it would only be a matter of exposing those features in a react-y way.

**Comment by scamden** [comment]
So right off the bat even on mobile with only one column showing I can scroll fast enough on react virtualized to create a flicker. You will never see empty areas and flicker in the grid because it uses a different method of virtualization from most libraries out there. I’ve seen the method used by react virtualized in a few other implementations and while this is a particularly good version of that method it has the inherent flaw of flickering on fast scrolls. I’m not saying you will never see jitter in the grid. If you render complex enough content you could depending on your machine but it will never render empty areas and in most cases it gets a consistent 30fps. Happy to discuss in more detail if you like in terms of differences but there’s a start.

**Comment by alexkrolick** [comment]
Is it possible to render React components into the grid cells?

The use case is to build something like this:

- 10k rows, 100 columns
- Fixed header
- Fixed left column
- Some cells contain `a` tags or React Router `Link` components 
- Some cells may have a tooltip or similar UI element on hover

**Comment by scamden** [comment]
It can def handle that size. In fact the only real limitation on size would be the memory usage not the grid speed and that limit would be an extremely large grid. In terms of rendering react components the grid handles complex content by using “builders” so yes you can render a tags and other rom elements but you will need to keep the elements up to date based on the state of the virtual scroll. The grid will call update on the builder with the appropriate data and the previously rendered element. Builders are documented over in the grid repo but the pattern def takes a second to grok so I’m happy to answer questions there. I haven’t yet tried rendering react components in builders but I will likely need to soon so I’m happy to help you tackle trying it out.

**Comment by scamden** [comment]
Oh and ya fixing columns and headers is trivial

**Comment by alexkrolick** [comment]
Hmm, I'm trying it out in a Codepen and the UMD build seems broken: 

https://codepen.io/alexkrolick/pen/goKJQB?editors=0010

This seems to be because the Webpack lib is only support commonjs externals: https://github.com/gridgrid/grid-react-adapter/blob/master/webpack/webpack.config.js#L308-L315

In general that Webpack config seems to be doing a lot of unnecessary work for a JS-only library (is it bundling the example HTML as well)?

**Comment by scamden** [comment]
Ah ya that makes sense. I’ve never tried it outside a webpack env. It is indeed bundling the html as well. In fact it’s a shared webpack config that we use across numerous projects to allow bundling both the test app and the lib, including libs that actually do have css and or html. I imagine webpack has a umd option for those externals I’ll look into making that change the next I’m by my laptop

**Comment by alexkrolick** [comment]
I'm able to import it into a webpack project. I tried passing a React element in the `formatted` attribute of some of the data, which predictably calls toString and returns `[object object]`. Any ideas on what would need to be done to get React to control those DOM elements? Off the top of my head it seems like doing that would require another semi-virtualization engine on top of this one.

**Comment by scamden** [comment]
@alexkrolick https://codepen.io/scamden/pen/BJPBNr

fixed your pen. the external issue was simple and you also had a small spelling and syntax error on the commented out import line.

**Comment by scamden** [comment]
@alexkrolick definitely it will be impossible to return an element from the data object, the formatted field must be a string as the types show. This is due to the difference in the virtualization approach the grid takes as compared to most other impls. It does not render everything and then remove and add elements dynamically. It actually only renders enough cells to fill the view and then reuses them, simulating a scroll by scrolling the content rather than moving the actual elements. It takes a second to get used to this paradigm but actually it's not terribly hard to work with once you do. (And it's blazing fast with O(1) scaling relative to the grid size)

The builder pattern is the only way to return elements to represent the cells of a column and yes it is virtualized in and of itself. Strictly speaking you could render decorators for every row but that will literally render an element for every row and in that sense will not be virtualized. Decorators are preferable for one off-y ui. The grid uses them to render the focus highlight or the selection range for example. But ya TLDR; as i mentioned previously the only performant way to render non-text content is using builders: https://github.com/gridgrid/grid#builders

The docs currently use angular as the rendering engine and as I said I have not yet tried using react here, but it should probably follow a very similar pattern to that shown in the docs. I'll do a little research to see if I can't determine the best way to handle this case since I'm definitely going to need it in the near future over here at CreditIQ anyway :)

**Comment by scamden** [comment]
@alexkrolick alright got a basic working prototype of rendering react components in builders. i'm sure there's a lot of tooling we could build to make this process easier (and safer, aka unmounting things on destroy etc), but at least this is a proof of concept:

https://codepen.io/scamden/pen/RxBbKj

**Comment by alexkrolick** [comment]
Ok, your Codepen looks good.  I will upgrade to 1.6.3. FYI I fixed the externals the same way in PR #2 earlier - I rebased it so now it is only adding an external for ReactDOM.

Based on your second Codepen I propose adding a `cellRenderer` [render prop](https://reactjs.org/docs/render-props.html) to the API that would work like this:

```jsx
class Example extends React.PureComponent {
  render() {
    return (
      <div>
        <ReactGridWrapper rows={rows} cols={cols} cellRenderer={(row, col, data) => {
            let result = data.formatted
            if (col % 2) result = <b>{result}</b>
            if (row % 2) result = <i>{result}</i>
            if (col === 0) result = <Link text={result} />
            return result
          }}/>
      </div>
    );
  }
}
```

I've created a wrapper implementing the render prop using `colBuilder` here:

https://codepen.io/alexkrolick/pen/RxBbJM?editors=0010

```jsx
class ReactGridWrapper extends React.Component {
  state = {
    cols: this.props.cols,
    rows: this.props.rows,
  };

  initModels() {
    const { cols, rows, cellRenderer } = this.props;
    if (!this.grid) return {cols, rows};
    const colBuilder = this.grid.colModel.createBuilder(
      () => document.createElement("div"),
      (element, { data, virtualCol, virtualRow }) => {
        ReactDOM.render(cellRenderer(virtualRow, virtualCol, data), element);
        return element;
      }
    );

    return {
      cols: cols.map(col => ({ ...col, builder: colBuilder })),
      rows: rows,
    }
  }

  componentDidMount() {
    const {cols, rows} = this.initModels();
    this.setState({ cols, rows });
  }

  render() {
    const { rows = [], cols = [] } = this.state;
    return (
      <ReactGrid
        rows={rows}
        cols={cols}
        ref={c => {
          this.grid = c ? c.grid : null;
        }}
      />
    );
  }
}
```

**Comment by scamden** [comment]
Oh funky I missed that pr. Happy to merge when I’m back by laptop.

I like this idea a lot. It’ll prob work but I’ll need to review the grid’s
rendering code because this has the downside of forcing a builder for every
column and therefore rendering at least a container div for every viewport
cell. I normally think of builders as “use sparingly” but this might
actually be ok. If not I bet we can work it out with some tweaks. Will take
a peak in the morning and let you know. Thanks for the suggestions! I
really appreciate the help working out the kinks and clarifying the api for
react!

**Comment by scamden** [comment]
Ok based on reviewing the code and some quick jsperf sanity checks I think this will be ok. We'll def need to test it out once its implemented for tricky perf situations. Did you want to try submitting a pr adding this to the official wrapper or want me to?

**Comment by alexkrolick** [comment]
Do you think it should be a separate component or just incorporate that API into the default implementation?

**Comment by scamden** [comment]
I think default probably makes sense. Obviously the prop should be optional
but ya why not

**Comment by alexkrolick** [comment]
Ok. I _may_ have bandwidth to work on it this week but I'm not sure if it will be a priority or not. I think the implementation is mostly inlining the wrapper and possibly adding hooks to recompute with `componentWillReceiveProps` or `componentDidUpdate`.

**Comment by scamden** [comment]
Absolutely. I’m also happy to take it on. Tbh was just leaving it open in
case you wanted the opportunity to contribute. It’s probably quicker for me
but let me know if you’re really interested in doing it.

**Comment by alexkrolick** [comment]
I don't mind if you go ahead and do it. As mentioned in #2 I am not able to reproduce the builds exactly in any case.

**Comment by scamden** [comment]
i'm gonna go ahead and close this but continue to open issues for anything you see that's missing
