### ISSUE TITLE
Cell renderer function not starting from row 0 if row 0 is a header

### ISSUE THREAD

**Issue by yashshah12** [gridgrid/grid-react-adapter#15]
I set my row[0].header = true, and then in my cell renderer function, it is not starting from row 0. 
I am trying to put my own styles on the header and in my cell renderer function, i check if row == 0 and then put those styles.

Is there a way to redesign the header cells?

**Comment by scamden** [comment]
well first off, if you're just applying style there are many css classes for your convenience. `.grid-cell` `.grid-is-header` `.grid-col-header` etc. please let me know if there's a particular style you're trying to achieve and can't because i'm aware that the way the grid virtualizes makes the styling a little confusing. I'm happy to advise. it's definitely preferable to use these classes rather than an element in the cellRenderer for perf reasons. I'd only use the cellRenderer if you 100% have to because the content is more complex than text. I've been meaning to document the css classes that are available along with maybe even providing some scss mixins for the more complex cases but haven't gotten to it. for now i can provide direct help and maybe we can document as we go.

that aside, this is due to the way @alexkrolick and i implemented cell renderer. internally it uses a colBuilder and colBuilders default to excluding the headers. normally the simpler approach is to create a rowBuilder for the whole header row since it's often a totally different type of content. we could make the change to always include the headers for this, or we could add a headerRowRenderer. whattya think alex?

**Comment by alexkrolick** [comment]
`headerRowRenderer` sounds good, I think headers and data are separate enough that making special cases in the `cellRenderer` is less ergonomic

**Comment by scamden** [comment]
ya that was my leaning as well. i'll work on that soon. hit my up for style stuff in the meantime @yashshah12

**Comment by scamden** [comment]
will be fixed by https://github.com/gridgrid/grid-react-adapter/pull/16

**Comment by yashshah12** [comment]
Awesome, thanks
